import { Anek_Latin } from "next/font/google";
import "../globals.css";
import { Links } from "./links";
const inter = Anek_Latin({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <aside className="aside">
            <h3>Dashboard</h3>
            <Links></Links>
        </aside>
        {children}
        </body>
    </html>
  );
}
